---
chdir: "/home/minecraft/public_html"
environment: development
address: 0.0.0.0
port: 8080
timeout: 30
log: "/home/minecraft/public_html/log/thin.log"
pid: tmp/pids/thin.pid
max_conns: 1024
max_persistent_conns: 100
require: []
wait: 30
threadpool_size: 20
servers: 2
rackup: config.ru
daemonize: true
